server:
  port: ${PORT:8080}

spring:
  application:
    name: users-ms
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring-application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

springdoc:
  swagger-ui:
    path: /api/users/swagger-ui.html
  api-docs:
    path: /api/users/v3/api-docs

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: 127.0.0.1:2000